# Generated by Django 5.1 on 2024-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_bracket',
            field=models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56+', '56+')], default='unknown', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='exam_type',
            field=models.CharField(choices=[('Sub-professional', 'Sub-professional'), ('Professional', 'Professional')], default='unknown', max_length=16),
        ),
    ]
