# Generated by Django 5.1 on 2024-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_profile_age_bracket_remove_profile_exam_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_bracket',
            field=models.CharField(choices=[('0-17', '0-17 years'), ('18-24', '18-24 years'), ('25-34', '25-34 years'), ('35-44', '35-44 years'), ('45-54', '45-54 years'), ('55-64', '55-64 years'), ('65+', '65 years and over')], default='uknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
