# Generated by Django 5.1 on 2024-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_profile_full_name_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_bracket',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300),
        ),
    ]
