# Generated by Django 5.1 on 2024-08-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_bracket',
            field=models.CharField(choices=[('U18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-59', '45-59'), ('60+', '60+')], default='U18', max_length=5),
        ),
    ]
