# Generated by Django 5.1 on 2024-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_bracket',
            field=models.CharField(choices=[('U18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35 above', '35 and above')], default='U18', max_length=8),
        ),
    ]
